Khush Purohit - 250840125028
Nikhil Lendkar - 250840125031

In [40]:
import numpy as np      

Create a 3×3 array of all True Boolean values


In [41]:
b_arr = np.ones((3,3), dtype = bool)
b_arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract odd numbers from an array


In [42]:
arr = np.arange(12).reshape(3,4)
mask = arr%2!=0
mask

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [43]:
arr[mask]

array([ 1,  3,  5,  7,  9, 11])

Replace all odd numbers with -1

In [44]:
arr1 = arr[mask]
arr1

array([ 1,  3,  5,  7,  9, 11])

In [45]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Reverse columns of a 2D array

In [46]:
arr[:,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

Get indices of elements greater than 5

In [47]:
# print('arr : ',arr)
arr = np.array(arr)
# print('arr : ',arr)
result = np.where(arr>5, 1,0)
print('result : ',result)
# print('arr : ',arr[result])

result :  [[0 0 0 0]
 [0 0 1 1]
 [1 1 1 1]]


In [48]:
arr2 = np.arange(1,10).reshape(3,3)
arr2
# arr2 = np.argwhere(arr2>5)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2 = np.arange(1,10).reshape(3,3)
arr2 = np.where(arr2>5)
arr2

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [50]:
arr2

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

Access last row - last column

In [51]:
arr2[2:]

()

In [52]:
arr2[:,2:]

TypeError: tuple indices must be integers or slices, not tuple

Set 2:


Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]

?

Create a 5×5 array with 1 on border and 0 inside

In [63]:
arr2 = np.ones((5,5))

In [64]:
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
arr2[1:-1,1:-1] = 0


In [66]:
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Create a random array of 10×10: perform stats (min, max, mean, std)


In [73]:
arr_random = np.random.random((10,10))
arr_random

array([[0.49828085, 0.5866139 , 0.87786057, 0.71954153, 0.96712621,
        0.03276747, 0.9330539 , 0.42225295, 0.76523129, 0.1670296 ],
       [0.43694463, 0.9738515 , 0.19513048, 0.73418952, 0.69539534,
        0.24619097, 0.4606992 , 0.98151352, 0.68132379, 0.25046251],
       [0.61179417, 0.25451719, 0.950571  , 0.9786647 , 0.53684419,
        0.94505638, 0.31908841, 0.08259595, 0.89208596, 0.02048525],
       [0.59014445, 0.15836196, 0.48886682, 0.04738824, 0.2682091 ,
        0.01330007, 0.55713745, 0.16959554, 0.4487591 , 0.49233337],
       [0.74515   , 0.55091588, 0.28977659, 0.4269832 , 0.76301172,
        0.07727588, 0.53308446, 0.49082824, 0.87196106, 0.98663784],
       [0.30674834, 0.26315632, 0.11115317, 0.08744138, 0.78108728,
        0.67315242, 0.76358939, 0.76309066, 0.16251845, 0.39456105],
       [0.02454042, 0.23436041, 0.15358945, 0.70113522, 0.54240888,
        0.77614951, 0.72999382, 0.95728625, 0.93232651, 0.95836694],
       [0.3938871 , 0.32649763, 0.6061232

In [74]:
arr_random.min()

np.float64(0.013300074803027084)

In [75]:
arr_random.max()

np.float64(0.9866378414578807)

In [76]:
arr_random.mean()

np.float64(0.5165409478036035)

In [77]:
arr_random.std()

np.float64(0.30095167313088766)

Broadcast a 1D array over a 2D array [all possible scenarios]

In [81]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [89]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
brodcast = arr + arr2
brodcast

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

Sort a 2D array by column 1 [hint: check method argsort()]

In [85]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
sorted = arr2[:,0].argsort()
sorted

array([0, 1, 2])

In [112]:
arr2[sorted]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])