In [2]:
import numpy as np

In [4]:
arr_1d = np.array([1,2,3,4,5,6])
arr_1d+10

array([11, 12, 13, 14, 15, 16])

In [5]:
arr_1d - 5

array([-4, -3, -2, -1,  0,  1])

In [6]:
arr_1d > 5

array([False, False, False, False, False,  True])

In [7]:
arr_2d = np.arange(12).reshape(2,6)
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [8]:
arr_1d + arr_2d

array([[ 1,  3,  5,  7,  9, 11],
       [ 7,  9, 11, 13, 15, 17]])

In [13]:
arr = np.arange(10,12).reshape(2,1)
arr

array([[10],
       [11]])

In [14]:
arr * arr_2d

array([[  0,  10,  20,  30,  40,  50],
       [ 66,  77,  88,  99, 110, 121]])

In [15]:
arr

array([[10],
       [11]])

In [17]:
arr_1 = np.arange(12).reshape(4,3)
arr_2 = np.arange(12).reshape(3,4)
arr_1 + arr_2

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [21]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[4]

np.int64(5)

In [23]:
arr[-4]

np.int64(6)

In [24]:
arr[[5,2,7]]

array([6, 3, 8])

Slicing and Indexing

In [32]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr_2d[1,2]

np.int64(6)

In [34]:
arr_2d[-1]

array([7, 8, 9])

In [35]:
i_row = [0,0,2,2]
i_col = [0,2,0,2]

arr_2d[i_row,i_col]

array([1, 3, 7, 9])

In [36]:
arr_2d[1:2,1:2]

array([[5]])

In [42]:
arr_2d[::,::2]


array([[1, 3],
       [4, 6],
       [7, 9]])

In [43]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10])
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr1d[4]

np.int64(5)

In [45]:
arr1d[-4]

np.int64(7)

In [46]:
arr1d[4:8]

array([5, 6, 7, 8])

In [47]:
arr1d[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
arr1d[4:]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr1d[:8:2]

array([1, 3, 5, 7])

In [50]:
arr1d[-4:-1]

array([7, 8, 9])

In [51]:
mask = arr>5
mask

array([False, False, False, False, False,  True,  True,  True,  True])