In [36]:
import numpy as np
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
np.sum(arr)

np.int64(78)

In [38]:
np.sum(arr,axis=0)

array([15, 18, 21, 24])

In [39]:
np.sum(arr,axis=1)

array([10, 26, 42])

In [40]:
arr3d = np.arange(24).reshape(2,3,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
np.sum(arr3d, axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [42]:
min_val = np.min(arr, axis=0)
print(f'arr : {arr}')
min_val

arr : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([1, 2, 3, 4])

In [43]:
max_val = np.max(arr,axis=0)
max_val

array([ 9, 10, 11, 12])

In [44]:
np.prod(arr,axis=1)

array([   24,  1680, 11880])

In [45]:
np.mean(arr)

np.float64(6.5)

In [46]:
np.average(arr)

np.float64(6.5)

In [47]:
np.median(arr)

np.float64(6.5)

In [48]:
np.std(arr)

np.float64(3.452052529534663)

In [49]:
sin_values = np.sin(arr)

In [50]:
sin_values

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])

In [51]:
log_values = np.log(arr)
log_values

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [52]:
exp_values = np.exp(arr)
exp_values

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [53]:
power = np.power(arr,3)
power

array([[   1,    8,   27,   64],
       [ 125,  216,  343,  512],
       [ 729, 1000, 1331, 1728]])

In [54]:
sq_rt = np.sqrt(arr)
sq_rt

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [55]:
random_a = np.random.random((3,4))
random_a

array([[0.07176879, 0.67769565, 0.11865213, 0.51993964],
       [0.14573998, 0.73311806, 0.21237723, 0.64787865],
       [0.69389335, 0.34431537, 0.64375117, 0.23795973]])

In [58]:
np.ceil(random_a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
cumm_sum = np.cumsum(arr)
cumm_sum

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [60]:
np.cumprod(arr)

array([        1,         2,         6,        24,       120,       720,
            5040,     40320,    362880,   3628800,  39916800, 479001600])

In [61]:
zeroth = np.percentile(arr,0)
zeroth

np.float64(1.0)

In [63]:
h_th = np.percentile(arr,100)
h_th

np.float64(12.0)

In [64]:
mth = np.percentile(arr,50)
mth

np.float64(6.5)

In [66]:
def square(n):
    return n*n

sq_funciton = np.vectorize(square) #returns a function that can be applied on each ele of the arr
sq_funciton

In [67]:
squares = sq_funciton(arr)
squares

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])