In [2]:
import numpy as np

1. array(list/tuple)
2. arange(start,end)
3. random.random((row,col))
4. random.randint(low,high,size)
5. random.uniform(low,high,size)
6. linspace(low,high,size)

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
arr.shape

(4,)

In [8]:
arr_2d = np.array([[1,2,3],[1,2,3]])
arr_2d

array([[1, 2, 3],
       [1, 2, 3]])

In [9]:
arr_2d.shape

(2, 3)

In [12]:
arr_2d = np.array([1,2,3,4], dtype = float, ndmin = 4)
arr_2d

array([[[[1., 2., 3., 4.]]]])

In [14]:
arr_2d.ndim

4

In [17]:
arr_2d.size

4

In [25]:
# import random
np.random.random((1,2))

array([[0.18962794, 0.81181156]])

In [54]:
np.random.randint(1,11,10)

array([ 8,  4,  4,  5,  3,  3,  3, 10,  8,  6], dtype=int32)

In [56]:
arr1 = arr.astype(float)
arr1

array([1., 2., 3., 4.])

In [58]:
arr1.dtype

dtype('float64')

In [59]:
arr2 = np.array([1,2,3,4], dtype= float,ndmin = 4 )
arr2

array([[[[1., 2., 3., 4.]]]])

In [61]:
arr2.ndim

4

In [63]:
arr2.size

4

In [65]:
random_a = np.random.randint(10,40,10)
random_a

array([22, 29, 32, 12, 23, 15, 21, 14, 34, 32], dtype=int32)

In [ ]:
random_u = np.random.uniform()

In [67]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
zeros = np.ones((3,3))
zeros

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
ept = np.empty((4,3))
ept

array([[1.00322093e-311, 1.00322093e-311, 1.00322093e-311],
       [1.26974871e-321, 1.00158201e-311, 1.38133720e-047],
       [2.96123573e-032, 1.84779586e-076, 4.25505287e+174],
       [3.89489297e-033, 7.63224352e+169, 2.52701367e-052]])

In [72]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])