In [29]:
import numpy as np


In [30]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
arr = arr.transpose()

In [32]:
arr.ravel()

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [33]:
arr.ravel().ndim

1

In [60]:
arr1 = np.random.randint(10,40,12).reshape(4,3)
arr1

array([[10, 38, 39],
       [25, 36, 22],
       [35, 28, 36],
       [29, 21, 34]], dtype=int32)

In [37]:
arr 

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [62]:
arr1

array([[10, 38, 39],
       [25, 36, 22],
       [35, 28, 36],
       [29, 21, 34]], dtype=int32)

In [61]:
horizontal = np.hstack((arr,arr1))
horizontal

array([[ 0,  4,  8, 10, 38, 39],
       [ 1,  5,  9, 25, 36, 22],
       [ 2,  6, 10, 35, 28, 36],
       [ 3,  7, 11, 29, 21, 34]])

In [64]:
arr1 = np.sort(arr1, axis=1)
arr1

array([[10, 38, 39],
       [22, 25, 36],
       [28, 35, 36],
       [21, 29, 34]], dtype=int32)

In [65]:
arr1 = np.sort(arr1, axis=0)
arr1

array([[10, 25, 34],
       [21, 29, 36],
       [22, 35, 36],
       [28, 38, 39]], dtype=int32)

In [66]:
combined = np.concatenate((arr,arr1))
combined

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [10, 25, 34],
       [21, 29, 36],
       [22, 35, 36],
       [28, 38, 39]])