In [4]:
import numpy as np

In [31]:
arr = np.arange(12).reshape(3,4)
arr2 = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
mask = arr%2 != 0
odd = arr[mask]
odd

array([ 1,  3,  5,  7,  9, 11])

In [11]:

arr[mask] = -1
arr

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

In [30]:
arr2

(array([1, 1, 2, 2, 2, 2]), array([2, 3, 0, 1, 2, 3]))

In [19]:
arr2[::, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [24]:
# mask = arr>5
# arr2[mask]
temp = np.where(arr2>5)
temp

(array([1, 1, 2, 2, 2, 2]), array([2, 3, 0, 1, 2, 3]))

In [32]:
arr2 = np.where(arr2>5)


In [33]:
arr2

(array([1, 1, 2, 2, 2, 2]), array([2, 3, 0, 1, 2, 3]))

In [5]:
arr3 = np.array([1,2,3,4,5,6])

In [6]:
arr3

array([1, 2, 3, 4, 5, 6])

In [8]:
arr3[1]

np.int64(2)

In [9]:
arr3[-1]

np.int64(6)

In [10]:
arr3[1:3]

array([2, 3])

In [12]:
arr3[0:4:2]

array([1, 3])

In [14]:
arr3[::2]


array([1, 3, 5])

In [15]:
arr3[-5:-2]


array([2, 3, 4])

In [17]:
arr3[-2:-5:-1]

array([5, 4, 3])

In [20]:

arr3[[1,4,5]]

array([2, 5, 6])

In [22]:
arr3[arr3>3]

array([4, 5, 6])

In [28]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
type(arr_2d)

numpy.ndarray

In [30]:
type(arr3)

numpy.ndarray

In [32]:
arr_2d[0,2]

np.int64(3)

In [33]:
arr_2d[1,-1]

np.int64(6)

In [34]:
arr_2d[-2,-1]

np.int64(6)

In [35]:
arr_2d[1]

array([4, 5, 6])

In [36]:
arr_2d[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [38]:
a2 = arr_2d
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a2[:,::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [41]:
a2[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [42]:
a2[::,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [43]:
a2[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [44]:
a2[0:2,1:]

array([[2, 3],
       [5, 6]])

In [46]:
print(a2)
a2[0:2,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [47]:
a2[-3:-1,2:]

array([[3],
       [6]])

In [48]:
a2[::2,1:3]

array([[2, 3],
       [8, 9]])

In [50]:
print(a2)
a2[[0,1,2], [0,1,2]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [51]:
a2[[0,0,2,2], [0,2,0,2]]

array([1, 3, 7, 9])

In [53]:
a2[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [54]:
a2[a2>4]

array([5, 6, 7, 8, 9])

In [55]:
a2[[True,False,True]]

array([[1, 2, 3],
       [7, 8, 9]])

In [62]:
a2[1:2,::2]

array([[4, 6]])

In [68]:
a3 = np.random.random_integers(12,size=(4,3))
a3

C:\Users\dbda.STUDENTSDC\AppData\Local\Temp\ipykernel_17304\3704103248.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 12 + 1) instead
  a3 = np.random.random_integers(12,size=(4,3))


array([[ 3,  3,  4],
       [ 3,  2, 11],
       [ 9, 11,  9],
       [ 5,  5,  2]], dtype=int32)

In [74]:
a4 = a3[1]
a4[a4%2==1]

array([ 3, 11], dtype=int32)

In [77]:
a3[1][a3[1]%2==1]


array([ 3, 11], dtype=int32)